; ============================================================
; BAI THUC HANH 7 - GIAI DOAN 1
; Mo ta: Web GUI co ban - ESP32 WiFi + WebSocket 1 servo
; Phan cung: ESP32 DevKit V1 + PCA9685 + Servo 0 (Base)
; Giao thuc: WebSocket plain-text (M <joint> <angle>)
; ============================================================

[env:esp32dev]
platform          = espressif32
board             = esp32dev
framework         = arduino
upload_speed      = 921600
monitor_speed     = 115200
upload_port       = COM9      ; <-- DOI THANH COM PORT THUC TE CUA BAN

lib_deps =
    esphome/AsyncTCP                      ; Thu vien TCP bat dong bo (yeu cau cua ESPAsyncWebServer)
    ottowinter/ESPAsyncWebServer-esphome  ; HTTP Server + WebSocket cho ESP32
    adafruit/Adafruit PWM Servo Driver Library ; Dieu khien PCA9685
