; === LAB 6 - STAGE 2 ===
; Dieu khien 6 khop Robot Arm qua Blynk IoT
; Platform: ESP32 DevKit V1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
upload_port = COM9           ; <-- DOI THANH COM PORT THUC TE CUA BAN
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    blynkkk/Blynk
