[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
upload_port = COM9           ; <-- DOI THANH COM PORT THUC TE CUA BAN
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
