; === BAI THUC HANH 6 - GIAI DOAN 3 ===
; Hoan thien he thong IoT - Web + Mobile + Auto Reconnect
; Platform: ESP32 DevKit V1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
upload_port = COM9           ; <-- DOI THANH COM PORT THUC TE CUA BAN
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    blynkkk/Blynk
